export const TABLE_HEADERS = {
    USERS: [
        {
            id: 'id',
            label: 'ID',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '20%',
        },
        {
            id: 'username',
            label: 'Username',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'email',
            label: 'Email',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '20%',
        },
        {
            id: 'roles',
            label: 'Roles',
            type: 'array',
            labelAlign: 'justify-right',
            dataAlign: 'right',
            width: '20%',
        },
        {
            id: 'departments',
            label: 'Departments',
            type: 'array',
            labelAlign: 'justify-right',
            dataAlign: 'right',
            width: '20%',
        },
    ],

    MOVIES: [
        {
            id: 'id',
            label: 'ID',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '5%',
        },
        {
            id: 'name',
            label: 'Name',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'director',
            label: 'Director',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'actors',
            label: 'Actors',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'author',
            label: 'Author',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'description',
            label: 'Description',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'dub',
            label: 'Dub',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'subTitle',
            label: 'Subtitle',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'duration',
            label: 'Duration',
            type: 'text',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'genres',
            label: 'Genres',
            type: 'array',
            labelAlign: 'justify-left',
            dataAlign: 'left',
            width: '10%',
        },
    ],

    FOOD: [
        {
            id: 'id',
            label: 'ID',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'name',
            label: 'Name',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '30%',
        },
        {
            id: 'image',
            label: 'Image',
            type: 'image',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '5%',
        },
        {
            id: 'foodType',
            label: 'Type',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '10%',
        },
        {
            id: 'description',
            label: 'Description',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '20%',
        },
        {
            id: 'amount',
            label: 'Amount',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '15%',
        },
    ],

    ROOMS: [
        {
            id: 'id',
            label: 'ID',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'roomNumber',
            label: 'Room number',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '20%',
        },
        {
            id: 'availableSeat',
            label: 'Total seat',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '20%',
        },

        {
            id: 'singleSeat',
            label: 'Single seat',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '20%',
        },

        {
            id: 'coupleSeat',
            label: 'Couple seat',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '15%',
        },
    ],

    TICKETS: [
        {
            id: 'id',
            label: 'ID',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'seatQnt',
            label: 'Seat qnt',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'foodQnt',
            label: 'Food qnt',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'discountQnt',
            label: 'Discount qnt',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'baseAmount',
            label: 'Base amount',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'totalAmount',
            label: 'Total amount',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'status',
            label: 'Status',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '10%',
        },
        {
            id: 'createdAt',
            label: 'Created at',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'expiryTime',
            label: 'Expiry time',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
    ],

    DISCOUNTS: [
        {
            id: 'id',
            label: 'ID',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '25%',
        },
        {
            id: 'foodType',
            label: 'Food type',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '25%',
        },
        {
            id: 'seatType',
            label: 'Seat type',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '25%',
        },
        {
            id: 'percentOff',
            label: 'Percent off',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '20%',
        },
    ],

    SCHEDULE: [
        {
            id: 'id',
            label: 'ID',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'movie.name',
            label: 'Name',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        }, 
        {
            id: 'roomNumber',
            label: 'Room',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '10%',
        },
        {
            id: 'showTime',
            label: 'Start',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'singleSeatPrice',
            label: 'Single seat price',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '10%',
        },
        {
            id: 'coupleSeatPrice',
            label: 'Couple seat price',
            type: 'text',
            labelAlign: 'justify-center',
            dataAlign: 'center',
            width: '10%',
        },
        {
            id: 'createdAt',
            label: 'Created at',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '15%',
        },
        {
            id: 'status',
            label: 'Status',
            type: 'text',
            labelAlign: 'justify-right',
            dataAlign: 'left',
            width: '10%',
        },
    ]
};

export const TABLE_HEADERS_KEYS = {
    TEXT: 'text',
    ARRAY: 'array',
    BOOLEAN: 'boolean',
    IMAGE: 'image',
};

// http://localhost:5006/payment/api/Payment/payment_result?vnp_Amount=14841000&vnp_BankCode=NCB&vnp_BankTranNo=VNP14643199&vnp_CardType=ATM&vnp_OrderInfo=6723384c38673ea681e94703&vnp_PayDate=20241031150034&vnp_ResponseCode=00&vnp_TmnCode=O6B1X7E4&vnp_TransactionNo=14643199&vnp_TransactionStatus=00&vnp_TxnRef=638659836018329558&vnp_SecureHash=8521507f58e8ee2ee2e03926ccbbf3cb3a4399682ac253ac4d141056f1cc25620513d00fc061bcf5028aef7bf2dc13a614fe5ae667fda0ea42499cb59fff93a1